version: "3.3"

volumes:
  redis:
  # The contents of /root, so that bash and ipython can store history
  web_home:

services:

  redis:
    image: redis:5.0.3
    volumes:
      - redis:/data:z


  web:
    build: ./
    environment:
      FLASK_ENV: development
      CONFIG_REDIS_URL: redis://redis:6379/0
      CONFIG_REDIRECT_URL: http://localhost:5000/redirect
    command: python3 flask_service.py
    volumes:
    - ./:/code
    ports:
      - "5000:5000"
    depends_on:
      - redis